server:
  port: 8081
  servlet:
    context-path: /orders-consumer

spring:
  application:
    name: orders-consumer
  liquibase:
    change-log: classpath:db/db.master.xml
    drop-first: false
    liquibase-schema: liquibase

orders:
  datasource:
    driver-class-name: org.postgresql.Driver
  hibernate:
    show_sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

kafka:
  order:
    group: OrdersConsumerGroup-1
    topic:
      published-order:
        name: orders.published
      created-order:
        name: orders.created
