server:
  port: 8080
  servlet:
    context-path: /orders-api
spring:
  application:
    name: orders-api

kafka:
  order:
    bootstrap-servers: localhost:9094
    topic:
      process-order: order.processing